### ISSUE TITLE
[Backend] Get logged in Admin details

### ISSUE THREAD

**Issue by jackfrost13** [HITK-TECH-Community/Community-Website#476] opened 2021-03-07 14:23 UTC
Use the existing `/admin` GET API to incorporate this. Use the `adminType` as self to respond with the details of logged-in admin

**Comment by SAEb-ai** [comment] 2021-03-08 13:29
@jackfrost13 Can I take up this issue?
Thanks!

**Comment by jackfrost13** [comment] 2021-03-12 10:23
@SAEb-ai please update status and open or

**Comment by raju-kr50** [comment] 2021-03-13 14:16
@jackfrost13 This issue is not assigned to anyone right now. So, is this issue resolved or still open for development.
If it is still open, can you please assign it to me to start working on it.

**Comment by jackfrost13** [comment] 2021-03-19 13:46
@raju-kr50 Please update your progress

**Comment by kumarshobhit** [comment] 2021-03-27 18:50
Hi I am a GSSOC participant. I would like to work on this issue.

**Comment by jackfrost13** [comment] 2021-03-28 12:33
@kumarshobhit Can you please share a timeline by which you can complete this? Due to this we are blocked on #467 and @akshitakanojia is waiting for this issue to be resolved

**Comment by kumarshobhit** [comment] 2021-03-28 12:57
Hi I am not able to login to the admin dashboard using dummy credentials. I have also written my problem on  the slack channel. 
Please check that.  I would be able to solve the issue then.

**Comment by jackfrost13** [comment] 2021-03-28 13:52
issue was resolved, please check again

**Comment by kumarshobhit** [comment] 2021-03-28 17:07
Yes it's working. Thank you

**Comment by kumarshobhit** [comment] 2021-03-30 14:17
Please reply so that I can solve this issue as quickly as possible.

**Comment by jackfrost13** [comment] 2021-03-30 14:52
Looks good to me but it shouldn't return an array. instead send just the object

**Comment by kumarshobhit** [comment] 2021-03-30 18:18
Ok noted. Working on it..

**Comment by jackfrost13** [comment] 2021-04-06 17:17
@kumarshobhit Please update if you are still working on this

**Comment by kumarshobhit** [comment] 2021-04-06 17:18
No I am not.. You may reassign it..

**Comment by akr-25** [comment] 2021-12-09 10:52
Was this issue resolved ?

**Comment by Shofiya2003** [comment] 2021-12-16 20:51
Hello,
Is this issue still open? If yes, can I work on it?

**Comment by AbhipsaGuru1012** [comment] 2021-12-23 17:30
> Was this issue resolved ?

No, the issue is still open.

**Comment by AbhipsaGuru1012** [comment] 2021-12-23 17:30
> Hello, Is this issue still open? If yes, can I work on it?

Sure, go ahead

**Comment by Shofiya2003** [comment] 2021-12-27 09:53
I tried requesting to the route /admin but it gives authentication error. I cannot figure out how to proceed. Need help.
Also wanted to know why the issue was reopened as someone already had a pull request merged. Thanks a ton.

**Comment by Kajol-Kumari** [comment] 2022-01-04 13:17
@Shofiya2003 you need auth token inorder to access the admin related APIs You can use below details for login in and get the token-
```
{
    "email" : "hitktechcommunity@gmail.com",
    "password" : "password"
}
```

The issue has been repoened as the merged pr had been reverted as it was not well reviewed and the code was not as per our standards.

**Comment by Gurdeep475** [comment] 2022-02-26 14:30
I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by Gurdeep475** [comment] 2022-02-27 15:01
@Kajol-Kumari thanks for assigning it to me. I will make PR after 1st march so that it will get considered in GSSOC`22.

**Comment by Gurdeep475** [comment] 2022-02-27 18:50
I am getting this error when I try to send adminType as self in query parameters
![image](https://user-images.githubusercontent.com/32095032/155895594-ea5f0cab-c7c6-4db2-965d-48bc5fac7e4e.png)

**Comment by Gurdeep475** [comment] 2022-02-27 19:47
I am unable to proceed as I am not able to send query params in the request URL. Please guide me.

**Comment by Gurdeep475** [comment] 2022-03-01 08:04
Please guide me, I am not able to send query params, getting pattern not match error.

**Comment by Gurdeep475** [comment] 2022-03-03 16:48
> Please guide me, I am not able to send query params, getting pattern not match error.

@Kajol-Kumari @jackfrost13 can you help me in this regard, the validation is not allowing me to pass query parameters.

**Comment by Gurdeep475** [comment] 2022-03-07 04:01
> Please guide me, I am not able to send query params, getting pattern not match error.

@Kajol-Kumari @jackfrost13 can you help me regarding this?

**Comment by Kajol-Kumari** [comment] 2022-03-08 13:32
> Please guide me, I am not able to send query params, getting pattern not match error.

@Gurdeep475 `type` accepts only `admin/superadmin` as the value that's why your request is failing. Please try with `type = admin`

**Comment by Gurdeep475** [comment] 2022-03-11 02:54
thanks, got it.

**Closed** 2022-03-23 12:30 UTC
Labels: enhancement, good first issue, backend, Level1, Swoc, CodePeak
