### ISSUE TITLE
Adding a space between the footer line and the email field

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [HITK-TECH-Community/Community-Website#986] opened 2024-05-29 08:46 UTC
**Describe your Proposal**
In the footer the gap between the email field and the footer last line is 0px i think it should increase .
**Additional context**
![Screenshot 2024-05-29 141459](https://github.com/HITK-TECH-Community/Community-Website/assets/118350936/ae471077-bb9f-44ea-abe2-8a9b0756ac13)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by Kajol-Kumari** [comment] 2024-05-29 17:02
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/802

**Closed by Kajol-Kumari** 2024-05-29 17:02 UTC
