### ISSUE TITLE
tags selected while asking the Q&A (ASK YOUR QUESTION) are not displaying in the Q&A cards as # 

### ISSUE THREAD

**Issue by ayushpatel1248** [HITK-TECH-Community/Community-Website#991] opened 2024-05-29 19:24 UTC
**Describe the bug**

- when user ask a question they select the tag example ml  and then submit the question
- this tags which were selected by user are not displayed in the card while displaying the question of user as card 
- only empty tags are displayed 

**To Reproduce**
1. analaysing the behaviour of code
2. wheather tags are sent to backend or not if not first sending it to backend and storing in the data base 
3. then sending the tags with the other field to the frontend from the backend 
4. now displaying the tags with hashtag sign in the cards with the other information

**Expected behavior**
cards should show the tags which were selected by the user when they submited the Q&A and they should be displayed with hashtag sign 

**Screenshots**
<img width="717" alt="Screenshot 2024-05-30 at 12 49 53 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/11c56825-2712-451d-861a-282a01e15861">
<img width="442" alt="Screenshot 2024-05-30 at 12 51 07 AM" src="https://github.com/HITK-TECH-Community/Community-Website/assets/127100604/e24f5cfd-42ec-4373-874e-c5ac7d81dcc6">

**Desktop (please complete the following information):**
 - OS:macos 
 - Browser chrome
 - Version 22

**Additional context**
please assign me this under level2 or level3 as it need  work of both frontend and backend

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

**Comment by Kajol-Kumari** [comment] 2024-05-31 04:59
Duplicate of #928

**Closed by Kajol-Kumari** 2024-05-31 04:59 UTC
Labels: bug
