### ISSUE TITLE
Replace twitter button with X in the footer

### ISSUE THREAD

**Issue by AkhilaSunesh** [HITK-TECH-Community/Community-Website#1010] opened 2024-06-03 01:38 UTC
**Describe the bug**
Replace twitter button with X in the footer

**Expected behavior**
It will be more professional and up-to-date.

**Screenshots**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/140897461/28b84eaa-7f2c-4158-9d01-c8efe248b961)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes

**Comment by Kajol-Kumari** [comment] 2024-06-03 16:56
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/987

**Closed by Kajol-Kumari** 2024-06-03 16:56 UTC
Labels: bug
