### ISSUE TITLE
Content Not In center

### ISSUE THREAD

**Issue by himanshu1221** [HITK-TECH-Community/Community-Website#811] opened 2023-02-18 16:29 UTC
**Describe the bug**

when we check the responsivenes the following content is not aligned in center as followed in the scrren shot 

**To Reproduce**
1. Go to 'Inspecting mode in your browser'
2. Click on 'select device galaxy s9+'
3. Scroll down to 'Below join us para'

**Expected behavior**

content should be aligned in the center but  it's not 

**Screenshots**

![Screenshot from 2023-02-18 21-53-28](https://user-images.githubusercontent.com/32031706/219876845-61ca11bf-a35f-46f2-bf4d-01a01cde566e.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [110.0.5481.100]

**Smartphone (please complete the following information):**
 - Device: [samsung galaxy s9+]
 - OS: [andoing oreo]
 - Browser [chrome]
 - Version [110.0.5481.65]

**Additional context**

i can fix this issue once yo assign me this issue and would be glad to work under JWOC 

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
YES

**Comment by deepbeatz** [comment] 2023-02-19 12:34
@himanshu1221  i want to work in this issue under JWOC

**Comment by Aarav238** [comment] 2023-02-20 04:37
please assign this issue to me @himanshu1221

**Comment by Harry629** [comment] 2023-02-22 19:13
I would like to work on this issue under JWOC.

**Comment by Kajol-Kumari** [comment] 2023-02-23 03:35
The style is as per the design and is not a bug. hence closing this issue

**Closed by Kajol-Kumari** 2023-02-23 03:35 UTC
Labels: bug
