### ISSUE TITLE
Small Hero and nav ui change

### ISSUE THREAD

**Issue by Sooraj002** [HITK-TECH-Community/Community-Website#941] opened 2024-05-21 03:58 UTC
**Describe your Proposal**
The Content of hero page and nav in mobile view isn't centered vertically, 
and also there navbar when opened doesn't cover the whole screen.

And also in footer Social-icons are not centered and the links can be arranged in more compact way.

**Additional context**
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/155e63f5-ce39-4d98-9230-562d6a27835f)
![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/0dfa7780-a057-4479-9346-ce5dc1bdaf1e)

![image](https://github.com/HITK-TECH-Community/Community-Website/assets/95868709/bbce469b-ac21-4909-80a6-814cf4ab6ee9)

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
yes

As it is not a major change i would like fix it, even if it doesn't count under Gssoc Contribution.

**Comment by Kajol-Kumari** [comment] 2024-05-22 16:26
Its intentional and its not a bug, so closing this

**Closed by Kajol-Kumari** 2024-05-22 16:26 UTC
