### ISSUE TITLE
[FEAT]: Integrating Docker into the project

### ISSUE THREAD

**Issue by Ratangulati** [HITK-TECH-Community/Community-Website#1034] opened 2024-06-10 01:54 UTC
Docker is a must for open-source projects nowadays as it has its benefits.

Use Case
Dockerfile has many benefits but consistency and isolation stand out the most.

Docker allows you to package your entire application, including its dependencies, into a single container. That makes sure your application will run across different environments.
another benefit is that it runs in its environment without interfering with other applications or the host system.

I will be creating and updating the docs and creating the Dockerfile for the project

**Comment by Kajol-Kumari** [comment] 2024-06-10 04:26
Duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/543

Thanks for opening the issue but please check once among the opened issues

**Closed by Kajol-Kumari** 2024-06-10 04:26 UTC
