### ISSUE TITLE
Bug in the Resources Form 

### ISSUE THREAD

**Issue by Ankur-Rai-19** [HITK-TECH-Community/Community-Website#953] opened 2024-05-22 18:02 UTC
## There is a bug in the Resources tab Form section. The alignment of the form is not in an appropriate way it requires some changes in it.

Bug Screenshot:
![HITK-Tech-Community Problem](https://github.com/HITK-TECH-Community/Community-Website/assets/125396300/eca7477c-8b89-4acc-952d-80927dc990e0)

**To Reproduce**
1. Go to the 'Resouces page or section'
2. Click on 'Form'

**Expected behavior**
## The alignment of the form should look like this:
![HITK-Tech-Community Sol](https://github.com/HITK-TECH-Community/Community-Website/assets/125396300/3fe53a98-23ac-45e3-a72b-66611dad5b13)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.

**Comment by Kajol-Kumari** [comment] 2024-05-23 09:29
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/935

**Closed by Kajol-Kumari** 2024-05-23 09:29 UTC
Labels: bug
