### ISSUE TITLE
No padding between email ID  and sign up buttons in footer section

### ISSUE THREAD

**Issue by rajRishi22** [HITK-TECH-Community/Community-Website#1007] opened 2024-06-02 12:17 UTC
**Describe the bug**
No padding between email ID  and sign up buttons in footer section

**To Reproduce**
1. Go to hosted website
2. Scroll down to the footer
4. See the error

**Expected behavior**
There should be proper padding between email id and submit buttons to the last line in footer.
**Screenshots**
![Screenshot 2024-06-02 174121](https://github.com/HITK-TECH-Community/Community-Website/assets/98014028/a80bbd7e-ddfa-429c-8f3c-49508305e28f)

**Comment by rajRishi22** [comment] 2024-06-02 12:18
Can you please assign me this issue?

**Comment by Kajol-Kumari** [comment] 2024-06-03 16:56
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/802

**Closed by Kajol-Kumari** 2024-06-03 16:56 UTC
Labels: bug
