### ISSUE TITLE
Allow user to like only once in Q&A section

### ISSUE THREAD

**Issue by kashish-51** [HITK-TECH-Community/Community-Website#961] opened 2024-05-24 08:41 UTC
In Q&A section a user can like multiple time and there is no restrictions but this should not be the case. One user should be allowed to like only once.
So, please assign this to me under GSSOC so that I can fix this.

**Comment by Kajol-Kumari** [comment] 2024-05-24 16:43
@kashish-51 this was supposed to be fixed using the cookies in https://github.com/HITK-TECH-Community/Community-Website/pull/942 pr, i would be more than happy if u can debug and fix the issue

**Comment by kashish-51** [comment] 2024-05-25 05:31
Thank you for assigning me

**Comment by aryansharma220** [comment] 2024-05-31 05:38
@Kajol-Kumari I would also like to work on this issue, if needed please assign it to me also.

**Comment by Kajol-Kumari** [comment] 2024-05-31 20:17
@kashish-51 can u please update on the progress of this issue?

**Comment by Vaishali-ajmera** [comment] 2024-06-28 10:35
@Kajol-Kumari Please assign this task to me. I will complete it in less amount of time.

**Comment by Vaishali-ajmera** [comment] 2024-07-02 12:40
There is some issue in the Q&A page. Page only is not showing.

**Comment by Kajol-Kumari** [comment] 2024-07-03 17:27
> There is some issue in the Q&A page. Page only is not showing.

As its a free deployment so the backend pod takes around 50 seconds to spin up when used after a long time, wait for that time, it will come up

**Comment by Kajol-Kumari** [comment] 2024-07-28 17:33
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/1004

**Closed by Kajol-Kumari** 2024-07-28 17:33 UTC
Labels: bug, level1, gssoc
