### ISSUE TITLE
Footer Enhancement 

### ISSUE THREAD

**Issue by alpharsh** [HITK-TECH-Community/Community-Website#1069] opened 2024-06-30 06:04 UTC
Inside the Input box Email ID is written in signup newsletter it would be example@gmail.com for a better CTA
![Screenshot 2024-06-30 113102](https://github.com/HITK-TECH-Community/Community-Website/assets/108024082/7d060808-d632-4fdc-a516-3017134994e8)

And the New and updated logo would be done of the X(Twitter)
![Screenshot 2024-06-30 113109](https://github.com/HITK-TECH-Community/Community-Website/assets/108024082/f957501c-efdc-4ce5-9a73-e9e5bad78b3a)

**Comment by alpharsh** [comment] 2024-06-30 06:05
Please assign this issue to me I want to work on this

**Comment by Kajol-Kumari** [comment] 2024-06-30 07:19
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/802

**Closed by Kajol-Kumari** 2024-06-30 07:19 UTC
