### ISSUE TITLE
[Frontend] Enhancement in Resource sharing page

### ISSUE THREAD

**Issue by Kajol-Kumari** [HITK-TECH-Community/Community-Website#171] opened 2021-01-03 07:18 UTC
Deliverables:

- [ ] Make the `Resource-sharing` page UI better with the form being displaying over a card similar to the `login page`
- [ ] Also mould the form structure a bit by keeping following fields row-wise
 row 1 - Name and Email ID
 row 2 - Phone Number and Resource link
and keep one input-field per row for the rest

**Comment by shraddha-1402** [comment] 2021-01-03 09:16
Hey @Kajol-Kumari i would like to work on this. Can you assign me?

**Comment by kenkirito** [comment] 2021-01-03 11:29
assign me

**Comment by Utkarshn10** [comment] 2021-01-04 06:44
@Kajol-Kumari I am a Swoc participant and I would like to work on this issue.

**Comment by Kajol-Kumari** [comment] 2021-01-04 07:46
Sure @Utkarshn10 go ahead with this issue

**Comment by Utkarshn10** [comment] 2021-01-04 08:58
@Kajol-Kumari I changed the card but I the second task isn't clear. Could you please share a reference image.
![Capture](https://user-images.githubusercontent.com/58587256/103518023-10938c00-4e99-11eb-80a1-db9d61ef84e0.PNG)

**Comment by amanprateek123** [comment] 2021-01-05 04:20
@Kajol-Kumari  If the issue is not solved yet, then please assign this issue to me. I have a good hand on the frontend part.

**Comment by Utkarshn10** [comment] 2021-01-05 04:37
@Kajol-Kumari  This is how the resources page form looks like after the changes. Please confirm so that I can generate pr.
![2](https://user-images.githubusercontent.com/58587256/103606935-ba2c5900-4f3d-11eb-966e-fd11d38c573e.PNG)

**Comment by Kajol-Kumari** [comment] 2021-01-05 05:05
Hey @amanprateek123 we can't assign this issue to you as @Utkarshn10 is already working on it. Maybe you can try enhancing the FAQs page and if you come up with  a better Ui, I will surely add proper labels to it and merge it :)

**Comment by amanprateek123** [comment] 2021-01-05 05:10
Thank You @Kajol-Kumari for assigning this issue. I am looking forward to it. Once I setup the project and go through the source code, i will immediate start working on this issue.

**Comment by Utkarshn10** [comment] 2021-01-05 06:45
@Kajol-Kumari Done as suggested!
![3](https://user-images.githubusercontent.com/58587256/103614916-a4c02a80-4f4f-11eb-80b4-85baf58805fc.PNG)

**Comment by amanprateek123** [comment] 2021-01-05 06:49
@Kajol-Kumari  How is this UI of FAQ page? For any change please let me know.
![Screenshot from 2021-01-05 12-17-31](https://user-images.githubusercontent.com/42955585/103615267-4a739980-4f50-11eb-8fb4-936b280ff2aa.png)

**Comment by amanprateek123** [comment] 2021-01-05 07:14
@Kajol-Kumari  This is the mobile version of the FAQ page.



![faq_mobile](https://user-images.githubusercontent.com/42955585/103617180-cd4a2380-4f53-11eb-91fb-b184d36130d0.jpeg)

**Comment by yashsehgal** [comment] 2021-01-08 06:44
Can I work on this issue?

**Closed** 2021-01-08 07:17 UTC
Labels: DWOC, Level-3, NO MORE ASSIGNMNET, SWOC, frontend
