### ISSUE TITLE
Send welcome email to user's upon subscribing to newsletter

### ISSUE THREAD

**Issue by vansh-codes** [HITK-TECH-Community/Community-Website#1059] opened 2024-06-18 14:55 UTC
**Is your feature request related to a problem? Please describe.**
As this is a community website, it would be great when the members receive constant email through newsletter. Also upon subscribing the user should get an instant welcome email greeting them and introducing them to the purpose of the newsletter.

**Describe the solution you'd like**
Adding instant reply feature using nodemailer in the backend services to send instant email to the user on subscribing to the newsletter.

**Describe alternatives you've considered**

**Additional context**

**Have you read the [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md)?**
Write your answer here.
Yes i have read the code of conduct for this project.

**Comment by Kajol-Kumari** [comment] 2024-06-22 14:48
duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/870

**Closed by Kajol-Kumari** 2024-06-22 14:48 UTC
