### ISSUE TITLE
[Frontend] Integrating the POST Resource with the form

### ISSUE THREAD

**Issue by TG922** [HITK-TECH-Community/Community-Website#793] opened 2022-04-21 21:22 UTC
### Deliverables:
 
- [ ]  Integrate the https://hitk-tech-community.netlify.app/resources form with backend [POST] api
 
 Ref - https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/resources/addResource.js

**Comment by Kajol-Kumari** [comment] 2022-04-22 04:48
@TG922 this is duplicate of https://github.com/HITK-TECH-Community/Community-Website/issues/759 
Please feel free to claim it and raise the pr for the same

**Comment by TG922** [comment] 2022-04-22 09:01
Ok @Kajol-Kumari

**Closed** 2022-04-26 05:44 UTC
